# ─── Serviços (Web) ─────────────────────────────────────────────────────
services:
  # Backend Nest.js
  - name: paggo-backend
    type: web
    plan: starter
    region: oregon
    branch: main
    runtime: node
    buildCommand: |
      cd backend
      npm install --legacy-peer-deps
      npm run build
    startCommand: |
      cd backend
      npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: paggo-db
          property: connectionString
      - key: JWT_SECRET
        value: "${JWT_SECRET}"
      - key: OCR_SPACE_KEY
        value: "${OCR_SPACE_KEY}"
      - key: OPENAI_API_KEY
        value: "${OPENAI_API_KEY}"

  # Frontend Next.js
  - name: paggo-frontend
    type: web
    plan: starter
    region: oregon
    branch: main
    runtime: node
    buildCommand: |
      cd frontend
      npm install --legacy-peer-deps
      npm run build
    startCommand: |
      cd frontend
      npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://paggo-backend.onrender.com"

# ─── Banco de dados Postgres gerenciado ─────────────────────────────────
databases:
  - name: paggo-db
    plan: starter

